### ISSUE TITLE
pytorch-transformers updated???

### ISSUE THREAD

**Issue by juanluis17** [Shivampanwar/Bert-text-classification#1]
Hi, the link to pregenerate_training_data.py does not exist. Could you please update it?
Thank you.

**Comment by Shivampanwar** [comment]
Hi, the library has changed. You can explore transformers more to find about finetuning. Here is the link which you can try :  [https://github.com/huggingface/transformers/tree/master/examples#language-model-training](url)
Another alternative which I would recommend is to do pip install pytorch-transfomers  and you will get the code of the previous version of the library itself locally where you will find pregenerate_training_data.py
